Correct SERREAS derivation in ael03
insightsengineering/tlg-catalog pull request #284
Opened 2024-11-12 12:44 UTC by Melkiades

Fixes #269

2024-11-22 11:02 UTC, pawelru commented on book/listings/adverse-events/ael03.qmd
> +
```suggestion
```

2024-11-22 21:17 UTC, edelarua requested changes
Looks good! Just a few small suggestions, and can you please update the snapshot as well? Then it should be good to go!

2024-11-22 21:17 UTC, edelarua commented on book/listings/adverse-events/ael03.qmd
> +adae$AESCONG[which(adae$AESER == "Y")[seq(3)]] <- "Y" # To mimick correct possibility of overlap
Spelling
```suggestion
adae$AESCONG[which(adae$AESER == "Y")[seq(3)]] <- "Y" # To mimic possibility of overlap
```

2024-11-22 21:17 UTC, edelarua commented on book/listings/adverse-events/ael03.qmd
> +# out |> select(AESDTH, AESLIFE, AESHOSP, AESDISAB, AESCONG, AESMIE, SERREAS)
Remove commented code
```suggestion
```

2024-11-22 21:17 UTC, edelarua commented on book/listings/adverse-events/ael03.qmd
> +
Empty line
```suggestion
```

2024-11-26 05:55 UTC, shajoezhu commented
hi @Melkiades , can you update the snapshot please. Thank you!

2024-12-02 12:29 UTC, pawelru approved these changes

2024-12-02 15:18 UTC, merged