replace ATOXGR and BTOXGR with ANRIND and BNRIND.
insightsengineering/tlg-catalog pull request #73
Opened 2023-07-19 15:22 UTC by ayogasekaram

closes #68

2023-07-20 16:09 UTC, edelarua approved these changes
Lgtm! Just one suggestion to convert low/high labels to uppercase :)

2023-07-20 16:09 UTC, edelarua commented on book/tables/lab-results/lbt15.qmd
>      abnormal = list(low = "LOW", high = "HIGH"),
Just a suggestion - I think this has been changed to uppercase in most tables 
```suggestion
    abnormal = list(Low = "LOW", High = "HIGH"),
```

2023-08-02 14:28 UTC, Melkiades requested changes
@ayogasekaram could you also update the snapshots?

2023-08-02 14:50 UTC, ayogasekaram commented
@Melkiades there are no changes to the output table so the snapshot is the same.

2023-08-03 14:48 UTC, Melkiades approved these changes
Lgtm!! Thanks Abi :)

2023-08-03 14:49 UTC, merged